### ISSUE TITLE
Error processing video file #2

### ISSUE THREAD

**Issue by hugomcruz** [hugomcruz/ffprobe-python#2]
Oct 01 01:06:46 onedrive-processor file-processors[onedrive-picture-processor-28268 2023-10-01 01:06:46,703 [INFO] [root] process_file(): Processing file: 20230930_184605000_iOS.MOV
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268 Traceback (most recent call last):
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 592, in <module>
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     mainProcessor()
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 585, in mainProcessor
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     process_onedrive_folder(origin_client, source_path, destination_client, destination_path + profile_destination_folder, config)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 513, in process_onedrive_folder
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     process_onedrive_folder(onedrive_origin_client, new_path, onedrive_destination_client, destination_path, config)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 513, in process_onedrive_folder
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     process_onedrive_folder(onedrive_origin_client, new_path, onedrive_destination_client, destination_path, config)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 532, in process_onedrive_folder
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     process_file(onedrive_origin_client, source_path + "/" + item["name"], onedrive_destination_client, destination_path, config)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 490, in process_file
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     process_video_file(onedrive_origin_client, source_file, onedrive_destination_client, destination_path, config)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 417, in process_video_file
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     new_filename = video_filename(filename)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "onedrive_processor.py", line 387, in video_filename
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     date_obj = video_creation_datetime(filename)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "/app/bin/onedrive-picture-processor-main/video_processing.py", line 33, in video_creation_datetime
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     metadata=FFProbe(filepath)
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268   File "/app/lib/ffprobe-python-master/ffprobe/ffprobe.py", line 96, in __init__
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268     self.metadata[m.groups()[0]] = m.groups()[1].strip()
Oct 01 01:06:50 onedrive-processor file-processors[onedrive-picture-processor-28268 AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by hugomcruz** [comment]
Temporary fix. Check if the group is empty before trying to access.
REPEATED
